version: '3.8'


configs:
  traefik_config:
    file: config.yml

services:
    traefik:
        image: traefik:v2.6
        ports:
          - target: 80
            published: 80
         # - target: 8080
         #   published: 8080
         #   protocol: tcp
         #   mode: host
         # - target: 443
         #   published: 443
         #   protocol: tcp
         #   mode: host
        configs:
          - source: traefik_config
            target: /data/traefik/config.yml
        command:
          - "--api=true"
          - "--api.insecure=true"
          - "--api.dashboard=true"
          - "--providers.docker=true"
          - "--providers.docker.swarmMode=true"
          - "--providers.docker.exposedByDefault=false"
          - "--providers.docker.network=proxy"
          #- "--providers.file.filename=/data/traefik/config.yml"
          - "--providers.file.watch=true"
          - "--entrypoints.web.address=:80"
          #- "--entrypoints.web.http.redirections.entryPoint.to=websecure"
          #- "--entrypoints.web.http.redirections.entryPoint.scheme=https"
          #- "--entrypoints.websecure.address=:443"
          - "--accesslog"
          - "--log.level=info"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock:ro
          - traefik:/data/traefik
        networks:
          - proxy
        deploy:
            mode: global
            placement:
                constraints:
                    - node.role == manager
            labels:
              # Dashboard
              - "traefik.enable=true"
              - "traefik.docker.network=proxy"
              - "traefik.http.routers.traefik.rule=Host(`traefik_env.mindworking.local`)"
              #- "traefik.http.routers.traefik.service=api@internal"
              #- "traefik.http.routers.traefik.tls.certresolver=default"
              #- "traefik.http.routers.traefik.entrypoints=websecure"
              #- "traefik.http.routers.traefik.middlewares=authtraefik"
              #- "traefik.http.middlewares.authtraefik.basicauth.users=admin:$apr1$YB1NE2uA$gTSDP0SScemBSIUuOkst5."
              #- "traefik.http.routers.traefik.entrypoints=admin"
              - "traefik.http.services.traefik.loadbalancer.server.port=8080"
              - "traefik.http.routers.traefik.entrypoints=web"
              # global redirect to https
              #- "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
              #- "traefik.http.routers.http-catchall.entrypoints=web"
              #- "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
              # middleware redirect
              #- "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

networks:
    proxy:
        external: true
volumes:
    traefik:
