- name: Set vm.max_map_count
  sysctl:
    name: vm.max_map_count
    value: '262144'
    state: present
    reload: yes

- name: Check vm.max_map_count in sysctl.conf
  command: grep 'vm.max_map_count' /etc/sysctl.conf
  register: grep_output
  changed_when: "'vm.max_map_count = 262144' not in grep_output.stdout"

- name: Report vm.max_map_count setting
  debug:
    msg: "{{ grep_output.stdout }}"