---
- name: Update Swarm Nodes
  hosts: swarm_managers:swarm_workers
  gather_facts: true
  become: yes

  tasks:
    - name: Iterate over Worker Nodes
      block:
        - name: Drain, Upgrade, and Activate Worker Nodes
          command:
            cmd: docker node update --availability drain {{ item }}
          with_items: "{{ groups['swarm_workers'] }}"
          loop_control:
            loop_var: worker_node
          when: inventory_hostname in groups['swarm_managers']

        - name: Include Update Role for Worker Node
          include_role:
            name: upgrade-packages
          with_items: "{{ groups['swarm_workers'] }}"
          loop_control:
            loop_var: worker_node
          when: inventory_hostname in groups['swarm_managers']

        - name: Bring Worker Node Back to Active
          command:
            cmd: docker node update --availability active {{ item }}
          with_items: "{{ groups['swarm_workers'] }}"
          loop_control:
            loop_var: worker_node
          when: inventory_hostname in groups['swarm_managers']

      when: inventory_hostname in groups['swarm_managers']