# this traefik reverse proxy has a bunch of features:
# - reverse proxy all 80/443 ingress traffic on a swarm
# - dynamic config via each app's swarm service labels
# - HA multi-container design for traefik
# - runs traefik on host NIC directly, to improve performance
#    and capture client IP's
# - uses consul to store static config for startup
# - uses haproxy to allow offloading traefik to worker nodes
# - store consul data in a volume on cloud storage with rexray

# TODO improvements
# make consul HA
# properly handle service restarts if init container config changes
# use envvars for email and default domain settings

version: '3.7'

x-default-opts:
  &default-opts
  logging:
    options:
      max-size: "1m"

services:
  traefik:
    image: traefik:v2.6
    command:
      - --providers.docker=true
      - "--providers.docker.swarmMode=true"
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      #- --entrypoints.websecure.address=:443
      - "--api=true"
      - --api.insecure=true
      - --api.dashboard=true
      #- --api.debug=true
      - "--providers.file.watch=true"
      - "--providers.docker.network=proxy"
      - "--accesslog"
      - "--log.level=info"
      # Add more settings specific to Traefik v2.6 as needed
    networks:
      - proxy
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    deploy:
      mode: global
      labels:
        - traefik.enable=true
        - traefik.http.routers.traefik.rule=Host(`traefik.dogvs.cat`)
        # Add more Traefik labels and settings as needed
        # Example:
        # - traefik.http.routers.traefik.tls=true

  consul:
    image: consul
    command: agent -server -dev
    networks:
      - traefik-consul
    volumes:
      - consul:/consul/data
    deploy:
      mode: global

  dockersocket:
    image: tecnativa/docker-socket-proxy
    networks:
      - traefik-docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      # Update as necessary for Traefik v2.6
      # Example:
      - SOCKET_TIMEOUT=2s
      - SOCKET_MAX_CONCURRENT=100
    deploy:
      mode: global
      placement:
        constraints: [node.role == manager]

volumes:
  consul:
    driver: local

networks:
  proxy:
    driver: overlay
    name: proxy
  traefik-consul:
    driver: overlay
    driver_opts:
      encrypted: 'true'
  traefik-docker:
    driver: overlay
    driver_opts:
      encrypted: 'true'
