- name: Check if Docker is installed
  command: docker --version
  register: docker_version
  failed_when: false
  changed_when: false

- name: Set Docker installation status
  set_fact:
    docker_installed: "{{ docker_version.rc == 0 }}"
  when: docker_version.stdout is defined

- block:
    - name: Install Docker Python library
      become: true
      become_method: sudo
      pip:
        name: docker

    - name: Remove old versions of Docker
      become: true
      become_method: sudo
      apt:
        state: absent
        pkg:
          - docker
          - docker-engine
          - docker.io
          - containerd
          - runc
        force_apt_get: true

    - name: Install required packages
      apt:
        name: lsb-release,ca-certificates,apt-transport-https,software-properties-common
        state: present
        update_cache: yes

    - name: Add Docker GPG apt Key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
        keyring: /usr/share/keyrings/docker-archive-keyring.gpg

    - name: Add Docker repository to APT sources list
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
        state: present
        filename: docker

    - name: Update APT cache
      become: true
      apt:
        update_cache: yes

    - name: Check Docker package policy
      command: apt-cache policy docker-ce
      become_user: root

    - name: Install Docker CE
      apt:
        name: docker-ce
        state: present
        update_cache: yes

    - name: Add "{{ansible_user}}" user to "docker" group
      become: true
      become_method: sudo
      shell: "adduser {{ansible_user}} docker"

    - name: Waiting for Docker service to become available
      wait_for:
        path: /var/run/docker.sock

    - name: Create the directory for Docker Compose plugins
      file:
        path: "~/.docker/cli-plugins"
        state: directory
      become: true

    - name: Download Docker Compose binary
      get_url:
        url: "https://github.com/docker/compose/releases/download/v2.16.0/docker-compose-linux-x86_64"
        dest: "~/.docker/cli-plugins/docker-compose"
      become: true

    - name: Set execute permissions for Docker Compose
      file:
        path: "~/.docker/cli-plugins/docker-compose"
        mode: "+x"
      become: true

  when: docker_installed == false