version: "3.8"

configs:
  index_html:
    file: index.html

services:
  nginx: 
    image: nginxdemos/hello
    configs:
      - source: index_html
        target: /usr/share/nginx/html/index.html
    networks: 
      - mynet
      - proxy
    deploy:
      mode: replicated
      replicas: 3
      update_config: 
        parallelism: 2 
        delay: 10s
      restart_policy: 
        condition: on-failure 
        delay: 5s 
        max_attempts: 3 
      placement:
        constraints: [node.role == worker]
      labels:
          - traefik.enable=true
          - traefik.docker.network=proxy
          - 'traefik.http.routers.nginx.rule=Host(`hello.mindworking.local`)'
          - traefik.http.routers.nginx.entrypoints=web
          - traefik.http.services.nginx.loadbalancer.server.port=80
    environment:
      - TZ=Europe/Copenhagen
    

networks:
  mynet:
    driver: overlay
    attachable: true
  proxy:
    external: true