---

- name: Upgrade all packages to the latest version
  become: true
  become_method: sudo
  apt:
    name: "*"
    state: latest
    force_apt_get: true
    update_cache: yes
  register: apt_upgrade  # This will capture the output of the upgrade task

- name: Reboot host(s) after package upgrade
  shell: sleep 2 && /sbin/shutdown -r now "ansible reboot request"
  async: 1
  poll: 0
  ignore_errors: true
  become: true
  become_method: sudo
  when: >
    apt_upgrade.changed and
    inventory_hostname != "127.0.0.1" and
    inventory_hostname != "localhost"
  # This conditional now includes a check to see if the apt task actually made changes

- name: Waiting for host(s) to reboot
  ansible.builtin.wait_for_connection:
    delay: 60
    timeout: 300
  when: >
    apt_upgrade.changed and
    inventory_hostname != "127.0.0.1" and
    inventory_hostname != "localhost"
  # This conditional ensures that waiting for reboot only happens if there was an upgrade and the host is not localhost
